### ISSUE TITLE
Large files are getting stuck in commit history

### ISSUE THREAD

**Issue by Minep** [StuPeter/Sougou_dict_spider#6]
It seems that there are huge amounts of Sougou's corpora that had been committed by accident (potentially relics from the time that this script was being debugged). And got "removed" in the later commit by simply another git push. 

However, this is never a true remove as git stores relative changes rather than a faithful snapshot of source-tree. Resulting an oversized repository (I got around 250MB of data downloaded when cloning this repository)

Some solutions that have come across my mind, just for reference:
1. Cherry-pick your commit into an orphaned branch, and purge the old branch entirely.
2. Just duplicate your source-tree into an orphaned branch
3. Doing an interactive rebase and amending the commit where large files getting committed into by rm it from git cache. (refer to: https://stackoverflow.com/a/2158271)

**Comment by StuPeter** [comment]
Thank you for your suggestion! I have already deleted the historical commits to prevent accidentally committing large amounts of Sougou's corpora to the repository. Thanks again for your advice!
